name: FTP Deploy project files

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: FTP Deploy (FTP-Deploy-Action)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./
          server-dir: /public_html/alrahma/ 
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/vendor/**
            **/storage/**
            **/tests/**
            **/node_modules/**
            .env
            .env.*
            **/*.log
            public/dashboard/assets/css/**/*
            public/dashboard/assets/fonts/**/*
            public/dashboard/assets/scss/**/*
          log-level: verbose

      - name: Deployment success check
        if: success()
        run: echo "✅ Deployment completed successfully!"      
